# Generated by Django 5.0.2 on 2024-03-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0010_guest_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='ful_name',
            field=models.CharField(db_column='full_name', max_length=60, verbose_name='Полное имя'),
        ),
    ]
