# Generated by Django 5.0.2 on 2024-03-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0011_alter_guest_ful_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='ful_name',
            field=models.CharField(max_length=60, verbose_name='Полное имя'),
        ),
    ]
