# Generated by Django 5.0.2 on 2025-03-10 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bath", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rotenburo",
            options={"verbose_name": "Ротенбуро", "verbose_name_plural": "Ротенбуро"},
        ),
    ]
